spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

pagination:
  cities:
    default:
      page: 0
      size: 20
      sort: id,asc